/* [Programmers] 164673. 조건에 부합하는 중고거래 댓글 조회하기 */

SELECT USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID, USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, "%Y-%m-%d")
FROM USED_GOODS_BOARD, USED_GOODS_REPLY
WHERE YEAR(USED_GOODS_BOARD.CREATED_DATE) = 2022
AND MONTH(USED_GOODS_BOARD.CREATED_DATE) = 10
AND USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID
ORDER BY USED_GOODS_REPLY.CREATED_DATE, USED_GOODS_BOARD.TITLE